apiVersion: apps/v1
kind: Deployment
metadata:
  name: oqqdlztl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oqqdlztl
  template:
    metadata:
      labels:
        app: oqqdlztl
    spec:
      containers:
      - image: okteto.dev/oqqdlztl:latest
        name: oqqdlztl
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d2647630-c30f-4467-8360-ee75a0e0e7f6"
        - name: Vless_Path
          value: "/mdvv"
        - name: Vmess_UUID
          value: "d2647630-c30f-4467-8360-ee75a0e0e7f6"
        - name: Vmess_Path
          value: "/iput"
        - name: Share_Path
          value: "/v2link"
